02333 Databar assignment task 3: src/kernel/kernel.h File Reference
src/kernel/kernel.h File Reference
This file holds kernel wide macros and declarations.
#include <sysdefines.h>
Data Structures
struct context
Defines an execution context.
union thread
Defines a thread.
struct process
Defines a process.
struct Elf64_Ehdr
Defines an ELF64 file header.
struct Elf64_Phdr
Defines an entry in the ELF program header table.
struct executable
Defines an executable program.
struct executable_image
Defines an executable image embedded into the kernel image.
struct CPU_private
Defines the structure pointed to by the kernel GS_BASE.
struct prepare_process_return_value
Helper struct that is used to return values from prepare_process.
Defines
#define SYSCALL_ARGUMENTS
Macro used in the system call switch to access the arguments to the system call.
#define KERNEL_VERSION (0x0000000100000000)
Kernel version number.
#define MAX_NUMBER_OF_PROCESSES (16)
Size of the process_table.
#define MAX_NUMBER_OF_THREADS (256)
Size of the thread_table.
#define EI_MAG0 0
The first four bytes in an ELF image is 0x7f 'E' 'L' 'F'.
#define EI_MAG1 1
#define EI_MAG2 2
#define EI_MAG3 3
#define EI_CLASS 4
The specific ELF image class.
#define EI_DATA 5
Describes if the image is big- or little- endian.
#define EI_VERSION 6
The version of the ELF specification the image adheres to.
#define EI_OSABI 7
Type of OS the image can be run on.
#define EI_ABIVERSION 8
Version of the ABI used.
#define EI_PAD 9
First unused byte in the identification array.
#define EI_NIDENT 16
Number of entries in the identification array.
#define PT_NULL 0
The entry is not used.
#define PT_LOAD 1
The segment can be loaded into memory.
#define PT_PHDR 6
The segment only hold a program header table.
#define PF_X 0x1
Segment can be executed.
#define PF_W 0x2
Segment can be written.
#define PF_R 0x4
Segment can be read.
#define PF_MASKPERM 0x0000FFFF
Used to mask the permission bits.
Functions
struct prepare_process_return_value prepare_process (const struct Elf64_Ehdr *elf_image, const unsigned int process, unsigned long memory_footprint_size)
Copies an ELF image to memory and prepares a process.
void cleanup_process (const int process)
This is the last thing that is run when a process terminates.
void initialize (void)
This function initializes the kernel after the assembly code portion has set the system and the CPU up.
int allocate_thread (void)
Allocate one thread.
void system_call_handler (void)
This function gets called from the assembly code and responds to the system calls.
int system_call_implementation (void)
This function gets called from the system call handler and implements system calls.
void timer_interrupt_handler (void)
This function gets called from the interrupt handler and manages timer interrupts.
void kprints (const char *const string)
Outputs a string to the bochs console.
void kprinthex (const register long value)
Prints a long formatted as a hexadecimal number to the bochs console.
void scheduler_called_from_system_call_handler (const register int schedule)
One of two entry points to the scheduler.
void scheduler_called_from_timer_interrupt_handler (const register int thread_changed)
One of two entry points to the scheduler.
static void outb (const register unsigned short port_number, const register unsigned char output_value)
Wrapper for a byte out instruction.
static void outw (const register unsigned short port_number, const register unsigned short output_value)
Wrapper for a word out instruction.
Variables
union thread thread_table [MAX_NUMBER_OF_THREADS]
Array holding all threads in the systems.
struct process process_table [MAX_NUMBER_OF_PROCESSES]
Array holding all processes in the system.
struct executable executable_table [MAX_NUMBER_OF_PROCESSES]
Array holding descriptions of all executable programs.
int executable_table_size
The number of executable programs in the executable_table.
struct executable_image * ELF_images_start
The first executable image in the linked list of executable images.
const char * ELF_images_end
The address of the first byte after the end of the last ELF image.
unsigned long first_available_memory_byte
The address of the first memory byte not used by any running process.
unsigned long memory_size
Size, in bytes, of the memory.
struct thread_queue ready_queue
The ready queue.
int timer_queue_head
The index, into thread_table, of the head of the timer queue.
long system_time
This variable holds the current system time.
struct CPU_private cpu_private_data
Holds data private to the CPU.
Detailed Description
This file holds kernel wide macros and declarations.
Definition in file kernel.h.
Define Documentation
#define EI_ABIVERSION 8
Version of the ABI used.
Definition at line 113 of file kernel.h.
#define EI_CLASS 4
The specific ELF image class.
Definition at line 107 of file kernel.h.
Referenced by initialize().
#define EI_DATA 5
Describes if the image is big- or little- endian.
Definition at line 108 of file kernel.h.
Referenced by initialize().
#define EI_MAG0 0
The first four bytes in an ELF image is 0x7f 'E' 'L' 'F'.
Definition at line 102 of file kernel.h.
Referenced by initialize().
#define EI_MAG1 1
Definition at line 104 of file kernel.h.
Referenced by initialize().
#define EI_MAG2 2
Definition at line 105 of file kernel.h.
Referenced by initialize().
#define EI_MAG3 3
Definition at line 106 of file kernel.h.
Referenced by initialize().
#define EI_NIDENT 16
Number of entries in the identification array.
Definition at line 116 of file kernel.h.
#define EI_OSABI 7
Type of OS the image can be run on.
Definition at line 112 of file kernel.h.
#define EI_PAD 9
First unused byte in the identification array.
Definition at line 114 of file kernel.h.
#define EI_VERSION 6
The version of the ELF specification the image adheres to.
Definition at line 110 of file kernel.h.
Referenced by initialize().
#define KERNEL_VERSION (0x0000000100000000)
Kernel version number.
Definition at line 20 of file kernel.h.
#define MAX_NUMBER_OF_PROCESSES (16)
Size of the process_table.
Definition at line 23 of file kernel.h.
Referenced by initialize().
#define MAX_NUMBER_OF_THREADS (256)
Size of the thread_table.
Definition at line 25 of file kernel.h.
Referenced by allocate_thread(), and initialize().
#define PF_MASKPERM 0x0000FFFF
Used to mask the permission bits.
Definition at line 178 of file kernel.h.
#define PF_R 0x4
Segment can be read.
Definition at line 177 of file kernel.h.
#define PF_W 0x2
Segment can be written.
Definition at line 176 of file kernel.h.
#define PF_X 0x1
Segment can be executed.
Definition at line 175 of file kernel.h.
#define PT_LOAD 1
The segment can be loaded into memory.
Definition at line 171 of file kernel.h.
Referenced by initialize(), and prepare_process().
#define PT_NULL 0
The entry is not used.
Definition at line 170 of file kernel.h.
Referenced by initialize().
#define PT_PHDR 6
The segment only hold a program header table.
Definition at line 172 of file kernel.h.
Referenced by initialize().
#define SYSCALL_ARGUMENTS
Value:
(thread_table[cpu_private_data.thread_index].\
                           data.registers.integer_registers)
Macro used in the system call switch to access the arguments to the system call.
Definition at line 15 of file kernel.h.
Referenced by system_call_handler(), and system_call_implementation().
Function Documentation
int allocate_thread (void) [inline]
Allocate one thread.
The allocated thread is not initialized. Rip and rflags need to be set for the thread to start properly.
Returns:
An index into thread_table or -1 if no thread could be allocated.
Definition at line 432 of file kernel.c.
References MAX_NUMBER_OF_THREADS, thread::owner, and thread_table.
void cleanup_process (const int process)
This is the last thing that is run when a process terminates.
It performs all cleanup activities. Right now it is empty but in assignment 4 it will, for example, release the memory owned by the process.
Parameters:
process The index, into process_table, of the terminating process.
Definition at line 176 of file kernel.c.
void initialize (void)
This function initializes the kernel after the assembly code portion has set the system and the CPU up.
Definition at line 181 of file kernel.c.
References cpu_private_data, thread::data, Elf64_Ehdr::e_ehsize, Elf64_Ehdr::e_flags, Elf64_Ehdr::e_ident, Elf64_Ehdr::e_machine, Elf64_Ehdr::e_type, Elf64_Ehdr::e_version, EI_CLASS, EI_DATA, EI_MAG0, EI_MAG1, EI_MAG2, EI_MAG3, EI_VERSION, executable::elf_image, executable_image::elf_image, ELF_images_end, executable_table, executable_table_size, prepare_process_return_value::first_instruction_address, context::integer_registers, kprints(), MAX_NUMBER_OF_PROCESSES, MAX_NUMBER_OF_THREADS, executable::memory_footprint_size, executable_image::next, outb(), thread::owner, Elf64_Phdr::p_filesz, Elf64_Phdr::p_flags, Elf64_Phdr::p_memsz, Elf64_Phdr::p_offset, Elf64_Phdr::p_type, Elf64_Phdr::p_vaddr, process::parent, prepare_process(), process_table, PT_LOAD, PT_NULL, PT_PHDR, ready_queue, thread::registers, context::rflags, context::rip, CPU_private::thread_index, thread_queue_init(), thread_table, and process::threads.
void kprinthex (const register long value)
Prints a long formatted as a hexadecimal number to the bochs console.
Parameters:
value the value to be written
Definition at line 68 of file kernel.c.
References outb().
Referenced by system_call_implementation().
void kprints (const char *const string)
Outputs a string to the bochs console.
Parameters:
string points to a null terminated string
Definition at line 49 of file kernel.c.
References outb().
Referenced by initialize(), and system_call_implementation().
static void outb (const register unsigned short port_number, const register unsigned char output_value) [inline, static]
Wrapper for a byte out instruction.
Definition at line 368 of file kernel.h.
Referenced by initialize(), kprinthex(), kprints(), and timer_interrupt_handler().
static void outw (const register unsigned short port_number, const register unsigned short output_value) [inline, static]
Wrapper for a word out instruction.
Definition at line 376 of file kernel.h.
Referenced by system_call_implementation().
struct prepare_process_return_value prepare_process (const struct Elf64_Ehdr * elf_image, const unsigned int process, unsigned long memory_footprint_size) [read]
Copies an ELF image to memory and prepares a process.
prepare_process does some checks to avoid that corrupt images gets copied to memory. However, the checks are not as thorough as the check in initialize.
Returns:
A prepare_process_return_value struct holding the first address of the process image and an address to the page table for the process.
Parameters:
elf_image Points to the ELF image to copy.
process The index of the process that is to be created.
memory_footprint_size Holds the maximum amount of memory, in bytes, the image is allowed to use.
Definition at line 83 of file kernel.c.
References first_available_memory_byte, prepare_process_return_value::first_instruction_address, memory_size, Elf64_Phdr::p_filesz, Elf64_Phdr::p_memsz, and PT_LOAD.
Referenced by initialize().
void scheduler_called_from_system_call_handler (const register int schedule)
One of two entry points to the scheduler.
This function is called at the end of the system call handler.
Parameters:
schedule 1 iff scheduling decisions have to be remade.
Definition at line 10 of file scheduler.c.
Referenced by system_call_handler().
void scheduler_called_from_timer_interrupt_handler (const register int thread_changed)
One of two entry points to the scheduler.
This function is called from the timer interrupt handler.
Parameters:
thread_changed 1 iff the interrupt code has updated scheduling data structures.
Definition at line 15 of file scheduler.c.
Referenced by timer_interrupt_handler().
void system_call_handler (void)
This function gets called from the assembly code and responds to the system calls.
Definition at line 450 of file kernel.c.
References ALL_OK, cpu_private_data, thread::data, context::from_interrupt, thread::list_data, thread::next, thread::registers, scheduler_called_from_system_call_handler(), SYSCALL_ARGUMENTS, SYSCALL_PAUSE, SYSCALL_TIME, system_call_implementation(), system_time, CPU_private::thread_index, thread_table, and timer_queue_head.
int system_call_implementation (void)
This function gets called from the system call handler and implements system calls.
The return value is not used until assignment 3.
< System calls may set this variable to 1. The variable is used as input to the scheduler to indicate if scheduling is necessary.
Definition at line 10 of file syscall.c.
References ALL_OK, ERROR_ILLEGAL_SYSCALL, kprinthex(), kprints(), outw(), SYSCALL_ARGUMENTS, SYSCALL_DEBUGGER, SYSCALL_PRINTHEX, and SYSCALL_PRINTS.
Referenced by system_call_handler().
void timer_interrupt_handler (void)
This function gets called from the interrupt handler and manages timer interrupts.
< Interrupt hander code may set this variable to 0. The variable is used as input to the scheduler to indicate if the interrupt code has updated scheduling data structures.
Definition at line 569 of file kernel.c.
References cpu_private_data, thread::data, thread::list_data, thread::next, outb(), ready_queue, scheduler_called_from_timer_interrupt_handler(), system_time, CPU_private::thread_index, thread_queue_enqueue(), thread_table, and timer_queue_head.
Variable Documentation
struct CPU_private cpu_private_data
Holds data private to the CPU.
Referenced by initialize(), system_call_handler(), and timer_interrupt_handler().
const char* ELF_images_end
The address of the first byte after the end of the last ELF image.
This variable is used for sanity checking.
Definition at line 37 of file kernel.c.
Referenced by initialize().
struct executable_image* ELF_images_start
The first executable image in the linked list of executable images.
Definition at line 35 of file kernel.c.
struct executable executable_table[MAX_NUMBER_OF_PROCESSES]
Array holding descriptions of all executable programs.
Definition at line 24 of file kernel.c.
Referenced by initialize().
int executable_table_size
The number of executable programs in the executable_table.
Definition at line 28 of file kernel.c.
Referenced by initialize().
unsigned long first_available_memory_byte
The address of the first memory byte not used by any running process.
This variable is used to implement a crude memory allocation scheme.
Definition at line 31 of file kernel.c.
Referenced by prepare_process().
unsigned long memory_size
Size, in bytes, of the memory.
Definition at line 33 of file kernel.c.
Referenced by prepare_process().
struct process process_table[MAX_NUMBER_OF_PROCESSES]
Array holding all processes in the system.
Definition at line 18 of file kernel.c.
Referenced by initialize().
struct thread_queue ready_queue
The ready queue.
Note:
Linked lists are terminated with a thread with a next index of -1.
Definition at line 21 of file kernel.c.
Referenced by initialize(), and timer_interrupt_handler().
long system_time
This variable holds the current system time.
The system time is the number of clock ticks since system start. There are 200 clock ticks per second.
Definition at line 44 of file kernel.c.
Referenced by system_call_handler(), and timer_interrupt_handler().
union thread thread_table[MAX_NUMBER_OF_THREADS]
Array holding all threads in the systems.
Definition at line 15 of file kernel.c.
Referenced by allocate_thread(), initialize(), system_call_handler(), thread_queue_dequeue(), thread_queue_enqueue(), and timer_interrupt_handler().
int timer_queue_head
The index, into thread_table, of the head of the timer queue.
The timer queue is a list of threads blocked waiting for the system clock to reach a certain time. This variable is set to -1 if there are no threads in the timer queue.
Definition at line 40 of file kernel.c.
Referenced by system_call_handler(), and timer_interrupt_handler().