02333 Databar assignment task 3: src/include/scwrapper.h File Reference
src/include/scwrapper.h File Reference
This file contains C wrapper functions for system calls.
#include "sysdefines.h"
Functions
static unsigned long version (void)
Wrapper for the system call that returns the version of the kernel.
static unsigned long prints (const char *const string)
Wrapper for the system call that prints a string.
static unsigned long printhex (const unsigned long value)
Wrapper for the system call that prints a hexadecimal value.
static unsigned long debugger (void)
Wrapper for the system call that invokes the bochs debugger.
static void terminate (void)
Wrapper for the system call that terminates threads and processes.
static unsigned long createprocess (const int executable)
Wrapper for the system call that creates processes.
static unsigned long pause (const int ticks)
Wrapper for the system call that pauses the process for a specified number of ticks.
static unsigned long time (void)
Wrapper for the system call that returns the current system time in ticks.
Detailed Description
This file contains C wrapper functions for system calls.
The wrappers are used by user programs to perform system calls from C.
Definition in file scwrapper.h.
Function Documentation
static unsigned long createprocess (const int executable) [inline, static]
Wrapper for the system call that creates processes.
Parameters:
executable integer identifying the program which should be loaded and run as a process.
Definition at line 80 of file scwrapper.h.
References SYSCALL_CREATEPROCESS.
Referenced by main().
static unsigned long debugger (void) [inline, static]
Wrapper for the system call that invokes the bochs debugger.
Definition at line 55 of file scwrapper.h.
References SYSCALL_DEBUGGER.
static unsigned long pause (const int ticks) [inline, static]
Wrapper for the system call that pauses the process for a specified number of ticks.
Parameters:
ticks integer holding the number of ticks the process should be paused.
Definition at line 96 of file scwrapper.h.
References SYSCALL_PAUSE.
Referenced by main().
static unsigned long printhex (const unsigned long value) [inline, static]
Wrapper for the system call that prints a hexadecimal value.
Parameters:
value Hexadecimal value to be printed.
Definition at line 43 of file scwrapper.h.
References SYSCALL_PRINTHEX.
static unsigned long prints (const char *const string) [inline, static]
Wrapper for the system call that prints a string.
Parameters:
string Pointer to the string to be printed.
Definition at line 29 of file scwrapper.h.
References SYSCALL_PRINTS.
Referenced by main().
static void terminate (void) [inline, static]
Wrapper for the system call that terminates threads and processes.
Definition at line 67 of file scwrapper.h.
References SYSCALL_TERMINATE.
static unsigned long time (void) [inline, static]
Wrapper for the system call that returns the current system time in ticks.
Definition at line 110 of file scwrapper.h.
References SYSCALL_TIME.
Referenced by main().
static unsigned long version (void) [inline, static]
Wrapper for the system call that returns the version of the kernel.
Definition at line 15 of file scwrapper.h.
References SYSCALL_VERSION.