02333 Databar assignment task 3: src/kernel/syscall.c File Reference
src/kernel/syscall.c File Reference
This files holds the implementations of all system calls.
#include "kernel.h"
Functions
int system_call_implementation (void)
This function gets called from the system call handler and implements system calls.
Detailed Description
This files holds the implementations of all system calls.
Definition in file syscall.c.
Function Documentation
int system_call_implementation (void)
This function gets called from the system call handler and implements system calls.
The return value is not used until assignment 3.
< System calls may set this variable to 1. The variable is used as input to the scheduler to indicate if scheduling is necessary.
Definition at line 10 of file syscall.c.
References ALL_OK, ERROR_ILLEGAL_SYSCALL, kprinthex(), kprints(), outw(), SYSCALL_ARGUMENTS, SYSCALL_DEBUGGER, SYSCALL_PRINTHEX, and SYSCALL_PRINTS.
Referenced by system_call_handler().